language: php
php:
    - 7.0
    - 7.1

branches:
    only:
        - master

matrix:
    include:
        - php: 7.0
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 7.1
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'

before_script:
    - composer update --prefer-source --dev

script:
    - bin/phpspec run -fpretty
